name: deploy-image

# Workflow when push action is requested
on:
  push:
    branches: master

jobs:
  automatic-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
           repository: "AmjadIG/tp-docker"
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.2
      -
        name: Docker Login
        uses: docker/login-action@v1.4.1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
      -
         name: Build and push Docker images
         uses: docker/build-push-action@v1.1.1
         with:
           context: .
           file: ./docker/Dockerfile
           push: true
           tags: menoueramjad/tp-devops
      -
         name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
